feeds:
- name: "ML Educational Series"
  author: "Silas Kwabla Gah"
  url: "https://kwablagah.substack.com/feed"
- name: "AI Echoes"
  author: "Benito Martin"
  url: "https://aiechoes.substack.com/feed"
- name: "The Neural Maze"
  author: "Miguel Otero"
  url: "https://theneuralmaze.substack.com/feed"
- name: "Decoding ML"
  author: "Paul Iusztin"
  url: "https://decodingml.substack.com/feed"
- name: "Swirl AI Newsletter"
  author: "Aurimas Griciūnas"
  url: "https://www.newsletter.swirlai.com/feed"
- name: "Marvelous MLOps Substack"
  author: "Başak Tuğçe Eskili and Maria Vechtomova"
  url: "https://marvelousmlops.substack.com/feed"
- name: "Jam with AI"
  author: "Shirin Khosravi Jam and Shantanu Ladhwe"
  url: "https://jamwithai.substack.com/feed"
- name: "Hamel's Substack"
  author: "Hamel Husain"
  url: "https://hamelhusain.substack.com/feed"
- name: "Neural Bits"
  author: "Alex Razvant"
  url: "https://multimodalai.substack.com/feed"
- name: "DiamantAI"
  author: "Nir Diamant"
  url: "https://diamantai.substack.com/feed"
- name: "ByteByteGo Newsletter"
  author: "Alex Xu"
  url: "https://blog.bytebytego.com/feed"
- name: "Latent.Space"
  author: "Latent.Space"
  url: "https://www.latent.space/feed"
- name: "Adaline Labs"
  author: "Adaline"
  url: "https://labs.adaline.ai/feed"
- name: "Gradient Ascent"
  author: "Sairam Sundaresan"
  url: "https://newsletter.artofsaience.com/feed"
- name: "Daily Dose of Data Science"
  author: "Avi Chawla"
  url: "https://blog.dailydoseofds.com/feed"
- name: "Generative AI for Everyone"
  author: "Hamza Farooq"
  url: "https://boringbot.substack.com/feed"
- name: "Vizuara's AI Newsletter"
  author: "Vizuara AI Labs"
  url: "https://www.vizuaranewsletter.com/feed"
- name: "Deep (Learning) Focus"
  author: "Cameron R. Wolfe, Ph.D."
  url: "https://cameronrwolfe.substack.com/feed"
- name: "Language Models & Co."
  author: "Jay Alammar"
  url: "https://newsletter.languagemodels.co/feed"
- name: "Exploring Language Models"
  author: "Maarten Grootendorst"
  url: "https://newsletter.maartengrootendorst.com/feed"
- name: "Hyperplane"
  author: "Cube Digital"
  url: "https://thehyperplane.substack.com/feed"
- name: "ModelCraft"
  author: "Abi Aryan"
  url: "https://modelcraft.substack.com/feed"
- name: "NeoSage"
  author: "Shivani Virdi"
  url: "https://blog.neosage.io/feed"
- name: "Nnitiwe's AI Blog"
  author: "Samuel Theophilus"
  url: "https://blog.nnitiwe.io/feed"
- name: "The Palindrome"
  author: "Tivadar Danka"
  url: "https://thepalindrome.org/feed"
- name: "Python & Chill"
  author: "Banias Baabe"
  url: "https://pythonandchill.substack.com/feed"
- name: "Rami's Data Newsletter"
  author: "Rami Krispin"
  url: "https://ramikrispin.substack.com/feed"
- name: "To Data & Beyond"
  author: "Youssef Hosni"
  url: "https://youssefh.substack.com/feed"
- name: "Vanishing Gradients"
  author: "Hugo Bowne-Anderson"
  url: "https://hugobowne.substack.com/feed"
- name: "When Engineers meet AI"
  author: "Kannan Kalidasan"
  url: "https://engineersmeetai.substack.com/feed"
- name: "slys.dev"
  author: "Anna & Jakub Slys"
  url: "https://iam.slys.dev/feed"
